apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraperprice
spec:
  schedule: "* 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraperprice
            image: gcr.io/pa5-crypto-advice2/cryptoadvice-scraper-price:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /conf
                name: confs
                readOnly: true 
              - mountPath: /tmp
                name: cache-volume
          restartPolicy: OnFailure
          volumes:
          - name: cache-volume
            emptyDir: {}
          - name: confs
            projected:
              sources:
              - secret:
                  name: gcp-key