apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: prediction
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: prediction
            image: gcr.io/pa5-crypto-advice2/cryptoadvice-prediction:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /conf
                name: confs
                readOnly: true 
              - mountPath: /tmp
                name: cache-volume
              - mountPath: /volume
                name: models-volume
          restartPolicy: OnFailure
          volumes:
          - name: cache-volume
            emptyDir: {}
          - name: models-volume
            emptyDir: {}
          - name: confs
            projected:
              sources:
              - secret:
                  name: gcp-key